### ISSUE TITLE
Zero downtime: Connected users should be able to continue working with osparc when osparc micro-services are restarted

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#2212] opened 2021-03-17 12:49 UTC
Use-case:

1. someone is connected to osparc, working with studies
2. the osparc-platform is re-deployed
3. the user of the osparc platform should continue to work seamlessly, maybe with a small acceptable glitch but it should definitely not complete with receiving 500 HTTP codes

## references:
[graylog entries](https://monitoring.osparc-master.speag.com/graylog/search?q=image_name%3Aitisfoundation%2A&rangetype=absolute&from=2021-03-17T11%3A15%3A09.608Z&to=2021-03-17T11%3A15%3A39.608Z) related to failed [e2e](https://git.speag.com/oSparc/e2e-testing/-/jobs/596639)

the e2e of isolve-mpi failed with the webserver returning a 500 for listing projects. one can see in the logs that the webserver was restarting at that moment.

Docker reference:
- docker swarm starts a new service (the replacing webserver) and waits until it is healthy. once healthy it closes the replaced service, waits 10seconds and then kills it if it is still around.

- [x] : restarting webserver works
- [ ] : restarting database
- [ ] : restarting other subsystems

**Comment by sanderegg** [comment] 2021-05-31 09:05
Testing like so:
- running a lot of sleepers
-> restarting the webserver seems to be ok
-> restarting the database restarts some of the computational services, but seems to generate issues loosing some states.

**Comment by GitHK** [comment] 2024-08-20 13:23
duplicate of #5614

**Closed by GitHK** 2024-08-20 13:23 UTC
Labels: a:infra+ops, a:frontend, a:webserver
