### ISSUE TITLE
Long running comp. services not removed or running forever

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#3162] opened 2022-07-04 08:44 UTC
`cc-2d` comp. services were running for up to 3 weeks on master consuming quite some cpu resources. Not sure how that happens. If they were still connected to the scheduler, we may want to set a maximum runtime (24 h?).

**Comment by sanderegg** [comment] 2023-05-17 15:06
duplicate of #3209

**Closed by sanderegg** 2023-05-17 15:06 UTC
Labels: bug
