### ISSUE TITLE
🐛 Bug in  `director_v2_core_computations:get_computation_task`: UNKNOWN running state reported

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#3201] opened 2022-07-20 11:01 UTC
In the logs of `director_v2_core_computations:get_computation_task`, the state might be reported as UNKNOWN (`state=<RunningState.UNKNOWN: 'UNKNOWN'>`), when a manual check with the DB shows it is actually `NOT_STARTED`

If this is somehow intentional and desired behavior, maybe consider making the log more intuitive to understand, since an UNKNOWN state seem like an error when reading the logs and does not help in tracing bug ;)

**Comment by sanderegg** [comment] 2023-04-06 08:50
we report UNKNOWN if for some reason the director-v2 could not be contacted, or in turns that the dask-scheduler could not be contacted.
I think that is a correct behavior as it is in effect really unknown.
I will try to improve the log if I manage.

**Comment by sanderegg** [comment] 2023-04-24 08:30
@mrnicegyu11 
Ok so I am now looking into this and I am not sure I understand the original issue. if you have some recollection  I would be happy to have a talk

**Comment by sanderegg** [comment] 2023-08-10 06:47
closing this case since it is staled and to my understanding works as intended until shown otherwise.

**Closed by sanderegg** 2023-08-10 06:47 UTC
Labels: bug, a:director-v2, a:dask-service
