### ISSUE TITLE
Logs from services are not delivered to correct browser window/tag

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#2976] opened 2022-04-08 09:48 UTC
# How to reproduce 

- open 2 browser windows
- in each one open a new project
- ad a service which produces some logs(run it if computational)

# What happens

- only one of the window will display logs inside it

**Comment by GitHK** [comment] 2022-06-10 14:11
@elisabettai you just reported on this today.

**Comment by sanderegg** [comment] 2022-07-28 05:58
duplicate of #2975

**Closed by sanderegg** 2022-07-28 05:58 UTC
Labels: bug, a:webserver
