### ISSUE TITLE
Issues in Retrieve/Refresh Postpro/Jupyter in Kember

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#773] opened 2019-05-14 11:58 UTC
## Long story short
If I/ a user clicks on retrieve and refresh several times, the behavior somehow changes and the system does not show me any data/results anymore.

## Expected behaviour
I can click retrieve and refresh as many times as I want and get the same consistent behavior.

## Actual behaviour
Please see movie:

![2019-05-14_13-53-39](https://user-images.githubusercontent.com/32800795/57696059-2d3dd900-7650-11e9-910f-17c38251e118.gif)

## Steps to reproduce
Once finished, retrieve and restart the PostPro viewer. Results are shown correctly. Then click on retrieve and refresh again.

## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "95352a0",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/95352a0/"
  },
  {
    "name": "osparc-simcore UI ['clean']",
    "version": "95352a0",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/95352a0/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "0.3.0-alpha.20190423-1234",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "qxapp",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-alpha-20190409-f79cc78",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.0.6",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.4",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.4.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.1.2",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "Ajv",
    "version": "6.5.0",
    "url": "https://github.com/epoberezkin/ajv"
  },
  {
    "name": "plotly",
    "version": "1.43.2",
    "url": "https://github.com/plotly/plotly.js"
  },
  {
    "name": "gridster",
    "version": "0.7.0",
    "url": "https://github.com/dsmorse/gridster.js"
  },
  {
    "name": "svg.js",
    "version": "2.6.4",
    "url": "https://github.com/svgdotjs/svg.js"
  }
]
```

**Comment by sanderegg** [comment] 2019-06-03 07:09
Analysis:
- Data is available
- the pipeline ran correctly and generated the data
What might have happened is that the data was deleted before being downloaded again (after calling the retrieve button). The refresh was done a bit too early and the data was not there yet. I could not reproduce the issue with a fresh pipeline.

**Comment by sanderegg** [comment] 2019-07-04 07:05
@drniiken @odeimaiz 
I discovered an issue lately within the webserver that might explain that the retrieve button does sometimes not work. We save the project every 5 seconds (@odeimaiz can confirm) and if one calls the retrieve button before the project was saved since the last change, then nothing seems to happen...

Also @drniiken maybe check if this issue still happen and if it is still relevant. If not I would close it.

**Comment by sanderegg** [comment] 2019-08-19 07:11
@drniiken this issue should now be completely fixed as the retrieve process is now done automatically.

**Closed** 2019-10-21 14:26 UTC
Labels: High Priority, ISAN, UX_improvements, dev:resolved, tester_review
