### ISSUE TITLE
When I write a comment I am "unknown" ?

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#4459] opened 2023-07-05 12:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which deploy/s?

other (e.g. local)

### Current Behavior

- I click on a project to open it
- I open the comments tab
- I write some comments
- I see I am "unknown" user...
![image](https://github.com/ITISFoundation/osparc-simcore/assets/35365065/83b1adaa-3125-4f7f-9e2a-c4cfceefc34c)

### Expected Behavior

my user name or user email should be visible

### Steps To Reproduce

- I click on a project to open it
- I open the comments tab
- I write some comments
- I see I am "unknown" user...

**Comment by matusdrobuliak66** [comment] 2023-07-05 15:26
Hi, this is strange that is happening locally because this feature is already deployed to all deployments including production, and seems it works correctly. "Unknown" should be shown only when the user was deleted from the database, which I guess is not your use-case as you are logged in. We can double-check with @odeimaiz how is it implemented, but I have the feeling as this is happening just locally, it means that how it is implemented on the frontend it expects something filled in the database that is not there.

**Comment by matusdrobuliak66** [comment] 2023-08-21 07:36
@odeimaiz do you have any idea why this might be happening when developing locally? thanks!

**Comment by odeimaiz** [comment] 2023-08-21 11:20
No really, since it was reported it only happens locally and I couldn't reproduce it, I ignored it. I could have another look...

**Comment by matusdrobuliak66** [comment] 2023-08-21 11:21
@odeimaiz  Ok, so just let me know please, otherwise I will just close it. I don't think this is important.

**Closed** 2024-11-06 08:18 UTC
Labels: bug
