### ISSUE TITLE
Proxy takes too long to be created

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#3325] opened 2022-09-06 12:18 UTC
After the containers start, it takes a very long time for the proxy to start.

This happens with very big studies when the deployment is running out of resources. It was noticed on multiple deployments. Primarly AWS Staging and master

How to reproduce. Open Prep2Go on master.

Low resource scenarios cause services to remain in pending for very long periods of time.

**Comment by sanderegg** [comment] 2022-10-17 14:21
duplicate of #3327

**Closed by sanderegg** 2022-10-17 14:21 UTC
