### ISSUE TITLE
Must click several times Yes to accept confirmation

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2742] opened 2022-01-14 10:45 UTC
in Master

![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/1f0228a5-95a0-4e7c-adb2-f3ff8bc9ddee)

**Comment by odeimaiz** [comment] 2022-01-14 10:50
Unable to reproduce... more information would be appreciated.
Was it a probe? An iterator converted into parameter and back several times?

**Comment by pcrespov** [comment] 2022-01-14 11:00
> Unable to reproduce... more information would be appreciated. Was it a probe? An iterator converted into parameter and back several times?

Just deleting an of the nodes

**Comment by odeimaiz** [comment] 2022-01-14 11:18
OK.... closing it since I'm not able to reproduce it.

**Comment by pcrespov** [comment] 2022-01-17 15:41
Modal dialog gets duplicated ... 
![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/bbbf46f2-e8f0-4f28-afdb-b734d00d5f29)

**Closed** 2022-02-04 17:09 UTC
Labels: bug
