### ISSUE TITLE
Refresh/Visual Issues in the GUI

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#772] opened 2019-05-14 11:46 UTC
## Long story short
For the last 2 days I'm experiencing some refresh and visual issues in the GUI, e.g., in the Dashboard.

## Expected behaviour
No issues :-)

## Actual behaviour
See image:
![Screenshot 2019-05-14 at 13 40 21](https://user-images.githubusercontent.com/32800795/57695463-a63c3100-764e-11e9-8393-feddff31b5ec.png)

## Steps to reproduce
I simply refreshed and logged in.

## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "95352a0",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/95352a0/"
  },
  {
    "name": "osparc-simcore UI ['clean']",
    "version": "95352a0",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/95352a0/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "0.3.0-alpha.20190423-1234",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "qxapp",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-alpha-20190409-f79cc78",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.0.6",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.4",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.4.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.1.2",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "Ajv",
    "version": "6.5.0",
    "url": "https://github.com/epoberezkin/ajv"
  },
  {
    "name": "plotly",
    "version": "1.43.2",
    "url": "https://github.com/plotly/plotly.js"
  },
  {
    "name": "gridster",
    "version": "0.7.0",
    "url": "https://github.com/dsmorse/gridster.js"
  },
  {
    "name": "svg.js",
    "version": "2.6.4",
    "url": "https://github.com/svgdotjs/svg.js"
  }
]
```

**Comment by drniiken** [comment] 2019-05-15 21:57
An update on this one:
This actually occurs in case too many own studies are accumulated and tried to be shown in the Dashboard. If there are too many, the thumbnails are not shown anymore. If I delete studies, it's getting fine again ...

**Comment by ignapas** [comment] 2019-06-07 12:05
I cannot reproduce this in any environment. If someone sees this problem please don't close your tab and call me. Nik does this happen everytime? Is it still ongoing?

**Comment by ignapas** [comment] 2019-06-12 12:50
I will try it in different browsers

**Comment by ignapas** [comment] 2019-06-25 15:16
This can be closed as it hasn't been seen in a long while...

**Closed** 2019-07-11 09:39 UTC
Labels: ISAN, Prio 1 Bug, UX_improvements, tester_review
