### ISSUE TITLE
Jupyter Service (M5; MS4.a,D4.b)

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#507] opened 2019-01-07 16:01 UTC
**Background**
The current Jupyter service should be finalized.

**Definition of Done**
- [x] Simplify mapping of input/output ports
- [x] Allow storing service along with python script, state (persistent)

**Comment by drniiken** [comment] 2019-05-16 09:45
Needs testing and decision if sufficient or needs change.

**Comment by KZzizzle** [comment] 2020-02-06 09:37
Can I close this as it is a duplicate of #1175?

**Closed** 2020-10-07 09:20 UTC
Labels: PO issue, dev:resolved
