### ISSUE TITLE
Redis locks might not be cleaned up

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#3105] opened 2022-06-15 14:06 UTC
On osparc-master, a large number of locks "CLOSING" are present in the redis (>100). They might properly disappear. It might be related to a restart of the webserver

![image](https://user-images.githubusercontent.com/8209087/173847073-a166c8ac-285a-4ab9-b5d6-00b0bf34a10d.png)

![image](https://user-images.githubusercontent.com/8209087/173847308-f5d5f777-d08a-4426-8368-65a62db52c6e.png)

Adding a timestamp to the lock might also aid debugging

**Comment by sanderegg** [comment] 2022-12-01 10:53
duplicate of https://github.com/ITISFoundation/osparc-issues/issues/724

**Closed by sanderegg** 2022-12-01 10:53 UTC
Labels: bug
