### ISSUE TITLE
REST API w/ Python Client (M10, MS6.1-3,D6.1-3)

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#503] opened 2019-01-07 16:01 UTC
**Background**
Allow oSPARC use through a non-GUI API (scripting, other). This includes creating a REST API as well as a Python client.

**Definition of Done**
Python interface can be used for:
- [ ] authentication
- [ ] load/save project
- [ ] setup pipeline
- [ ] display/export results

**Comment by pcrespov** [comment] 2020-02-05 11:30
This is a duplicate of osparc-issues#16

**Comment by pcrespov** [comment] 2020-02-05 12:57
duplicate of ITISFoundation/osparc-issues#16

**Closed by pcrespov** 2020-02-05 12:57 UTC
Labels: PO issue, duplicate
