### ISSUE TITLE
Dynamic Services are shut down in an open study when second tab with a second study is closed

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#2994] opened 2022-04-21 09:31 UTC
## Long story short

When you have oSparc open in two browser tab and close one, also the services corresponding to the project opened in the second tab will be closed. This results in the "Server Connection Error" in JupyterNotebooks

Please not that @GitHK and me investigated the garbage-colelctor logs, and the gargabe collector is not involved or responsible for this bug. @GitHK recons that likely a `on_user_logout` socket.io event is involved.

## Expected behaviour

Closing a tab does not affect a second study open in a second tab

## Actual behaviour

Closing a second tab affects unrelated studies of a user --> Dynamic Services (Jupyters) are (gracefully) shut down

## Steps to reproduce

- Open two projects in two browser tabs (no need to duplicate tab)
- Add a jupyter to each of them, open it
- Close one tab (forcefully) by pressing the "X" button in the browser
- Wait for the redis TTL timeout
- See that in the second (still open) tab, the jupyter will display "Server connection error", because it was shut down

## Your environment

- This was tested on dalco-production deployment

_reported by @Konohana0608_

**Comment by GitHK** [comment] 2022-05-04 05:26
To make sure let's also ask @odeimaiz on how to reproduce this, as he managed to do it once.

**Comment by sanderegg** [comment] 2023-05-17 15:08
this entry is one year old, and no one seems to be able to reproduce it. please close it
@mrnicegyu11 @odeimaiz or @GitHK

**Comment by GitHK** [comment] 2023-05-18 07:25
Just tested this on master, as instructed by the use case. Everything works as expected. I will close the issue.
If still present, please reopen it and update the case with your findings @mrnicegyu11 @odeimaiz

**Closed by GitHK** 2023-05-18 07:25 UTC
Labels: bug
