### ISSUE TITLE
Flaky tests/unit/test_tasks.py::test_run_computational_sidecar_real_fct[BootMode.CPU-integration.version.0]

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#4097] opened 2023-04-12 10:24 UTC
SEE https://github.com/ITISFoundation/osparc-simcore/actions/runs/4676931543/jobs/8283850475#step:9:682

```
FAILED tests/unit/test_tasks.py::test_run_computational_sidecar_real_fct[BootMode.CPU-integration.version.0] - AssertionError: Could not find '{"input_1": 23, "input_23": "a string input", "the_input_43": 15.0, "the_bool_input_54": false}' in worker_logs:
   ['Starting task for itisfoundation/sleeper:2.1.2 on fv-az1128-197...',
   "Pulling itisfoundation/sleeper:2.1.2: {'status': 'Pulling from itisfoundation/sleeper', 'id': '2.1.2'}...",
   "Pulling itisfoundation/sleeper:2.1.2: {'status': 'Digest: sha256:df5db962cb5b7ed3fcfdf4128764d4393d4f8d9fbe7dbc7cb0e91e0c3fab84a0'}...",
   "Pulling itisfoundation/sleeper:2.1.2: {'status': 'Status: Image is up to date for itisfoundation/sleeper:2.1.2'}...",
   'Docker image for itisfoundation/sleeper:2.1.2 ready  on fv-az1128-197.',
   "Downloading 'amount.js' into local file 'amount.js'...",
   "Downloading 'level.webm' into local file 'level.webm'...",
   "Downloading 'parent.html' into local file 'parent.html'...",
   "Downloading 'admit.gif' into local file 'admit.gif'...",
   "Downloading 'pressure.webm' into local file 'pressure.webm'...",
   "Downloading 'two.json' into local file 'two.json'...",
   "Downloading 'out.txt' into local file 'out.txt'...",
   "Downloading 'product.js' into local file 'product.js'...",
   "Downloading 'strategy.pptx' into local file 'strategy.pptx'...",
   "Downloading 'right.key' into local file 'right.key'...",
   "Downloading 'live.wav' into local file 'live.wav'...",
   "Downloading 'also.pptx' into local file 'also.pptx'...",
   "Downloading 'amount.js' into local file 'some_file_input_1'...",
   "Downloading 'level.webm' into local file 'some_file_input_2'...",
   "Downloading 'parent.html' into local file 'some_file_input_3'...",
   "Downloading 'admit.gif' into local file 'some_file_input_4'...",
   "Downloading 'pressure.webm' into local file 'some_file_input_5'...",
   "Downloading 'two.json' into local file 'some_file_input_6'...",
   "Downloading 'out.txt' into local file 'some_file_input_7'...",
   "Downloading 'product.js' into local file 'some_file_input_8'...",
   "Downloading 'strategy.pptx' into local file 'some_file_input_9'...",
   "Downloading 'right.key' into local file 'some_file_input_10'...",
   "Downloading 'live.wav' into local file 'some_file_input_11'...",
   "Downloading 'also.pptx' into local file 'some_file_input_12'...",
   "Downloading 'amount.js': 100.0% (207.0B / 207.0B) [0.00 MBytes/s (avg)]",
   "Downloading 'level.webm': 100.0% (252.0B / 252.0B) [0.00 MBytes/s (avg)]",
   "Downloading 'parent.html': 100.0% (235.0B / 235.0B) [0.00 MBytes/s (avg)]",
   "Downloading 'admit.gif': 100.0% (211.0B / 211.0B) [0.00 MBytes/s (avg)]",
   "Downloading 'pressure.webm': 100.0% (212.0B / 212.0B) [0.00 MBytes/s (avg)]",
   "Downloading 'two.json': 100.0% (236.0B / 236.0B) [0.00 MBytes/s (avg)]",
   "Downloading 'out.txt': 100.0% (243.0B / 243.0B) [0.00 MBytes/s (avg)]",
   "Downloading 'product.js': 100.0% (210.0B / 210.0B) [0.00 MBytes/s (avg)]",
   "Downloading 'strategy.pptx': 100.0% (214.0B / 214.0B) [0.00 MBytes/s (avg)]",
   "Downloading 'right.key': 100.0% (178.0B / 178.0B) [0.00 MBytes/s (avg)]",
   "Downloading 'live.wav': 100.0% (204.0B / 204.0B) [0.00 MBytes/s (avg)]",
   "Downloading 'also.pptx': 100.0% (202.0B / 202.0B) [0.00 MBytes/s (avg)]",
   "Downloading 'amount.js': 100.0% (207.0B / 207.0B) [0.00 MBytes/s (avg)]",
   "Downloading 'level.webm': 100.0% (252.0B / 252.0B) [0.00 MBytes/s (avg)]",
   "Downloading 'parent.html': 100.0% (235.0B / 235.0B) [0.00 MBytes/s (avg)]",
   "Downloading 'admit.gif': 100.0% (211.0B / 211.0B) [0.00 MBytes/s (avg)]",
   "Downloading 'pressure.webm': 100.0% (212.0B / 212.0B) [0.00 MBytes/s (avg)]",
   "Downloading 'two.json': 100.0% (236.0B / 236.0B) [0.00 MBytes/s (avg)]",
   "Downloading 'out.txt': 100.0% (243.0B / 243.0B) [0.01 MBytes/s (avg)]",
   "Downloading 'product.js': 100.0% (210.0B / 210.0B) [0.01 MBytes/s (avg)]",
   "Downloading 'strategy.pptx': 100.0% (214.0B / 214.0B) [0.01 MBytes/s (avg)]",
   "Downloading 'right.key': 100.0% (178.0B / 178.0B) [0.01 MBytes/s (avg)]",
   "Downloading 'live.wav': 100.0% (204.0B / 204.0B) [0.01 MBytes/s (avg)]",
   "Downloading 'also.pptx': 100.0% (202.0B / 202.0B) [0.01 MBytes/s (avg)]",
   "Downloading 'amount.js': 100.0% (207.0B / 207.0B) [0.00 MBytes/s (avg)]",
   "Download of 'amount.js' into local file 'amount.js' complete.",
   "Downloading 'level.webm': 100.0% (252.0B / 252.0B) [0.00 MBytes/s (avg)]",
   "Download of 'level.webm' into local file 'level.webm' complete.",
   "Downloading 'parent.html': 100.0% (235.0B / 235.0B) [0.00 MBytes/s (avg)]",
   "Download of 'parent.html' into local file 'parent.html' complete.",
   "Downloading 'admit.gif': 100.0% (211.0B / 211.0B) [0.00 MBytes/s (avg)]",
   "Download of 'admit.gif' into local file 'admit.gif' complete.",
   "Downloading 'pressure.webm': 100.0% (212.0B / 212.0B) [0.00 MBytes/s (avg)]",
   "Download of 'pressure.webm' into local file 'pressure.webm' complete.",
   "Downloading 'two.json': 100.0% (236.0B / 236.0B) [0.00 MBytes/s (avg)]",
   "Download of 'two.json' into local file 'two.json' complete.",
   "Downloading 'out.txt': 100.0% (243.0B / 243.0B) [0.00 MBytes/s (avg)]",
   "Download of 'out.txt' into local file 'out.txt' complete.",
   "Downloading 'product.js': 100.0% (210.0B / 210.0B) [0.00 MBytes/s (avg)]",
   "Download of 'product.js' into local file 'product.js' complete.",
   "Downloading 'strategy.pptx': 100.0% (214.0B / 214.0B) [0.00 MBytes/s (avg)]",
   "Download of 'strategy.pptx' into local file 'strategy.pptx' complete.",
   "Downloading 'right.key': 100.0% (178.0B / 178.0B) [0.00 MBytes/s (avg)]",
   "Download of 'right.key' into local file 'right.key' complete.",
   "Downloading 'live.wav': 100.0% (204.0B / 204.0B) [0.00 MBytes/s (avg)]",
   "Download of 'live.wav' into local file 'live.wav' complete.",
   "Downloading 'also.pptx': 100.0% (202.0B / 202.0B) [0.00 MBytes/s (avg)]",
   "Download of 'also.pptx' into local file 'also.pptx' complete.",
   "Downloading 'amount.js': 100.0% (207.0B / 207.0B) [0.00 MBytes/s (avg)]",
   "Download of 'amount.js' into local file 'some_file_input_1' complete.",
   "Downloading 'level.webm': 100.0% (252.0B / 252.0B) [0.00 MBytes/s (avg)]",
   "Download of 'level.webm' into local file 'some_file_input_2' complete.",
   "Downloading 'parent.html': 100.0% (235.0B / 235.0B) [0.00 MBytes/s (avg)]",
   "Download of 'parent.html' into local file 'some_file_input_3' complete.",
   "Downloading 'admit.gif': 100.0% (211.0B / 211.0B) [0.00 MBytes/s (avg)]",
   "Download of 'admit.gif' into local file 'some_file_input_4' complete.",
   "Downloading 'pressure.webm': 100.0% (212.0B / 212.0B) [0.00 MBytes/s (avg)]",
   "Download of 'pressure.webm' into local file 'some_file_input_5' complete.",
   "Downloading 'two.json': 100.0% (236.0B / 236.0B) [0.00 MBytes/s (avg)]",
   "Download of 'two.json' into local file 'some_file_input_6' complete.",
   "Downloading 'out.txt': 100.0% (243.0B / 243.0B) [0.00 MBytes/s (avg)]",
   "Download of 'out.txt' into local file 'some_file_input_7' complete.",
   "Downloading 'product.js': 100.0% (210.0B / 210.0B) [0.00 MBytes/s (avg)]",
   "Download of 'product.js' into local file 'some_file_input_8' complete.",
   "Downloading 'strategy.pptx': 100.0% (214.0B / 214.0B) [0.00 MBytes/s (avg)]",
   "Download of 'strategy.pptx' into local file 'some_file_input_9' complete.",
   "Downloading 'right.key': 100.0% (178.0B / 178.0B) [0.00 MBytes/s (avg)]",
   "Download of 'right.key' into local file 'some_file_input_10' complete.",
   "Downloading 'live.wav': 100.0% (204.0B / 204.0B) [0.01 MBytes/s (avg)]",
   "Download of 'live.wav' into local file 'some_file_input_11' complete.",
   "Downloading 'also.pptx': 100.0% (202.0B / 202.0B) [0.01 MBytes/s (avg)]",
   "Download of 'also.pptx' into local file 'some_file_input_12' complete.",
   'All the input data were downloaded.',
   'Starting to parse information of task [itisfoundation/sleeper:2.1.2 - a9be5d373e5fe3041e55574fa46ccb6b23f528a302045e7a505a[756](https://github.com/ITISFoundation/osparc-simcore/actions/runs/4676931543/jobs/8283850475#step:9:757)481099582/frosty_wescoff]',
   "Uploading 'log.dat' to 's3://simcore/log.dat'...",
   "Uploading 'log.dat': 0.0% (0 / NaN) [0.00 MBytes/s (avg)]",
   "Upload of 'log.dat' to 'log.dat' complete",
   'Finished parsing information of task [itisfoundation/sleeper:2.1.2 - a9be5d373e5fe3041e55574fa46ccb6b23f528a302045e7a505a756481099582/frosty_wescoff]',
   "Container started as 'a9be5d373e5fe3041e55574fa46ccb6b23f528a302045e7a505a756481099582' on fv-az1128-197...",
   'Container ran successfully.',
   'Completed run of docker.io/itisfoundation/sleeper:2.1.2',
   'Retrieving output data...',
   "Uploading 'a_outputfile' to 's3://simcore/output_file'...",
   "Uploading 'a_outputfile' to 's3://simcore/output_file'...",
   "Uploading 'output_file': 100.0% (30.0B / 30.0B) [0.01 MBytes/s (avg)]",
   "Uploading 'output_file': 100.0% (30.0B / 30.0B) [0.01 MBytes/s (avg)]",
   "Uploading 'output_file': 100.0% (30.0B / 30.0B) [0.01 MBytes/s (avg)]",
   "Uploading 'output_file': 100.0% (30.0B / 30.0B) [0.00 MBytes/s (avg)]",
   "Upload of 'a_outputfile' to 'output_file' complete",
   "Upload of 'a_outputfile' to 'output_file' complete",
   'All the output data were uploaded.',
   'retrieved outputs data:\n'
   '{\n'
   ' "pytest_string": "is quite an amazing feat",\n'
   ' "pytest_integer": 432,\n'
   ' "pytest_float": 3.2,\n'
   ' "pytest_bool": false,\n'
   ' "pytest_file": {\n'
   '  "url": "s3://simcore/output_file",\n'
   '  "file_mapping": "a_outputfile",\n'
   '  "file_mime_type": null\n'
   ' },\n'
   ' "pytest_file_with_mapping": {\n'
   '  "url": "s3://simcore/output_file",\n'
   '  "file_mapping": "subfolder/a_outputfile",\n'
   '  "file_mime_type": null\n'
   ' }\n'
   '}',
   'Task completed successfully.']
assert 0 > 0
 +  where 0 = len([])
============ 1 failed, 73 passed, 22 warnings in 230.20s (0:03:50) =============
```

**Comment by sanderegg** [comment] 2023-05-04 06:46
could not reproduce. closing.

**Closed** 2023-05-04 06:47 UTC
Labels: t:maintenance
