### ISSUE TITLE
enable DEV_FEATURES for the api-server in staging and production @pcrespov @bisgaard-itis

### ISSUE THREAD

**Issue by wvangeit** [ITISFoundation/osparc-simcore#5812] opened 2024-05-14 07:51 UTC

**Comment by bisgaard-itis** [comment] 2024-05-14 11:53
Closing this as it is a duplicate of https://github.com/ITISFoundation/osparc-issues/issues/1432

**Closed by bisgaard-itis** 2024-05-14 11:53 UTC
Labels: Meta-modeling
